/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TlsSettings } from './tls-configuration';

/**
 * API server configuration.
 */
export interface ApiSettings {
    /**
     * API base URL.
     */
    'base_url'?: string;
    /**
     * Authentication strategies.
     */
    'authentication_strategies'?: Array<ApiSettingsAuthenticationStrategiesEnum>;
    'tls'?: TlsSettings;
}

export const ApiSettingsAuthenticationStrategiesEnum = {
    JWT: 'jwt',
    MTLS: 'mtls'
} as const;

export type ApiSettingsAuthenticationStrategiesEnum = typeof ApiSettingsAuthenticationStrategiesEnum[keyof typeof ApiSettingsAuthenticationStrategiesEnum];


