/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Authentication configuration.
 */
export interface AuthSettings {
    /**
     * Auth provider.
     */
    'provider'?: AuthSettingsProviderEnum;
    /**
     * Allowed usernames.
     */
    'allowed_usernames'?: Array<string>;
}

export const AuthSettingsProviderEnum = {
    GITHUB: 'github',
    INSECURE_DISABLED: 'insecure_disabled'
} as const;

export type AuthSettingsProviderEnum = typeof AuthSettingsProviderEnum[keyof typeof AuthSettingsProviderEnum];


