/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Capability and routing information for CLI OAuth login.
 */
export interface CliAuthConfig {
    /**
     * Whether CLI OAuth login is currently available.
     */
    'enabled': boolean;
    /**
     * Canonical browser origin for the OAuth flow when enabled.
     */
    'web_url': string | null;
    /**
     * Authentication methods configured on the server.
     */
    'methods': Array<string>;
    /**
     * Optional machine-readable reason when CLI OAuth login is unavailable. Known values currently include `github_not_enabled` and `web_not_enabled`. 
     */
    'reason'?: string | null;
}

