/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for creating a new run, either from inline Graphviz source or from a local workflow path plus resolved settings.
 */
export interface CreateRunRequest {
    /**
     * Graphviz DOT language source defining the workflow graph.
     */
    'dot_source'?: string;
    /**
     * Absolute or relative path to the workflow file to load on the local machine.
     */
    'workflow_path'?: string;
    /**
     * Working directory used to resolve the workflow path.
     */
    'cwd'?: string;
    /**
     * JSON-serialized `fabro_types::Settings` payload resolved by the CLI.
     */
    'settings_json'?: string;
    /**
     * Optional pre-generated run ID to use instead of allocating a new ULID.
     */
    'run_id'?: string;
}

