/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for creating a new run from a Graphviz graph source.
 */
export interface CreateRunRequest {
    /**
     * Graphviz DOT language source defining the workflow graph.
     */
    'dot_source': string;
}

