/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GitAuthorSettings } from './git-author-configuration';
// May contain unused imports in some cases
// @ts-ignore
import type { WebhookSettings } from './webhook-configuration';

/**
 * Git provider configuration.
 */
export interface GitSettings {
    /**
     * Git provider.
     */
    'provider'?: GitSettingsProviderEnum;
    /**
     * GitHub App ID.
     */
    'app_id'?: string;
    /**
     * GitHub App Client ID.
     */
    'client_id'?: string;
    /**
     * GitHub App slug.
     */
    'slug'?: string;
    'author'?: GitAuthorSettings;
    'webhooks'?: WebhookSettings;
}

export const GitSettingsProviderEnum = {
    GITHUB: 'github'
} as const;

export type GitSettingsProviderEnum = typeof GitSettingsProviderEnum[keyof typeof GitSettingsProviderEnum];


