/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Portkey AI gateway configuration collected during browser install.
 */
export interface InstallPortkeyInput {
    /**
     * Portkey gateway base URL (e.g. https://api.portkey.ai/v1).
     */
    'url': string;
    /**
     * Portkey API key.
     */
    'api_key': string;
    /**
     * Provider adapter to use. One of: anthropic, openai, gemini, kimi, zai, minimax, inception.
     */
    'provider': string;
    /**
     * Portkey routing target (e.g. @bedrock-sandbox). Defaults to provider when omitted.
     */
    'provider_slug'?: string;
    /**
     * Portkey config ID or inline JSON for advanced routing (fallbacks, load balancing).
     */
    'config'?: string;
}

