/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InstallLlmProviderInput } from './install-llm-provider-input';
// May contain unused imports in some cases
// @ts-ignore
import type { InstallPortkeyInput } from './install-portkey-input';

/**
 * LLM providers selected during browser install. Provide direct provider keys, a Portkey gateway config, or both.
 */
export interface InstallLlmProvidersInput {
    'providers': Array<InstallLlmProviderInput>;
    /**
     * Optional Portkey AI gateway configuration. When provided, all LLM traffic routes through the Portkey gateway.
     */
    'portkey'?: InstallPortkeyInput;
}

