/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Portkey AI gateway configuration collected during browser install.
 */
export interface InstallPortkeyInput {
    /**
     * Portkey gateway base URL (e.g. https://api.portkey.ai/v1).
     */
    'url': string;
    /**
     * Portkey API key.
     */
    'api_key': string;
    /**
     * Portkey Model Catalog provider slug (e.g. @openai-prod, @bedrock-sandbox).
     */
    'provider_slug': string;
    /**
     * Optional native provider adapter. One of: anthropic, openai, gemini, kimi, zai, minimax, inception. Unlocks provider-specific features when set.
     */
    'provider'?: string;
    /**
     * Portkey config ID or inline JSON for advanced routing (fallbacks, load balancing).
     */
    'config'?: string;
}

