/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Internal stage status from outcomes and node status records.
 */

export const InternalStageStatus = {
    SUCCESS: 'success',
    FAIL: 'fail',
    SKIPPED: 'skipped',
    PARTIAL_SUCCESS: 'partial_success',
    RETRY: 'retry'
} as const;

export type InternalStageStatus = typeof InternalStageStatus[keyof typeof InternalStageStatus];



