/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * LLM provider and model settings.
 */
export interface LlmSettings {
    /**
     * Model identifier.
     */
    'model'?: string;
    /**
     * Provider name.
     */
    'provider'?: string;
    /**
     * Provider fallback chains.
     */
    'fallbacks'?: { [key: string]: Array<string>; };
}

