/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Local sandbox settings.
 */
export interface LocalSandboxSettings {
    /**
     * Git worktree mode for local sandbox.
     */
    'worktree_mode'?: LocalSandboxSettingsWorktreeModeEnum;
}

export const LocalSandboxSettingsWorktreeModeEnum = {
    ALWAYS: 'always',
    CLEAN: 'clean',
    DIRTY: 'dirty',
    NEVER: 'never'
} as const;

export type LocalSandboxSettingsWorktreeModeEnum = typeof LocalSandboxSettingsWorktreeModeEnum[keyof typeof LocalSandboxSettingsWorktreeModeEnum];


