/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeStatusRecord } from './node-status-record';

/**
 * Internal node projection state.
 */
export interface NodeState {
    'prompt'?: string | null;
    'response'?: string | null;
    'status'?: NodeStatusRecord | null;
    'provider_used'?: any;
    'diff'?: string | null;
    'script_invocation'?: any;
    'script_timing'?: any;
    'parallel_results'?: any;
    'stdout'?: string | null;
    'stderr'?: string | null;
}

