/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestRecord } from './pull-request-record';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestRef } from './pull-request-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestUser } from './pull-request-user';

/**
 * Stored pull request record plus live GitHub fields.
 */
export interface PullRequestDetail {
    'record': PullRequestRecord;
    'number': number;
    'title': string;
    'body'?: string | null;
    'state': string;
    'draft': boolean;
    'merged': boolean;
    'merged_at'?: string | null;
    'mergeable'?: boolean | null;
    'additions': number;
    'deletions': number;
    'changed_files': number;
    'html_url': string;
    'user': PullRequestUser;
    'head': PullRequestRef;
    'base': PullRequestRef;
    'created_at': string;
    'updated_at': string;
}

