/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Pull request creation configuration.
 */
export interface PullRequestSettings {
    /**
     * Whether to create a pull request after a successful run.
     */
    'enabled'?: boolean;
    /**
     * Whether to create the pull request as a draft.
     */
    'draft'?: boolean;
    /**
     * Whether to enable GitHub auto-merge on the created PR. Implies draft = false.
     */
    'auto_merge'?: boolean;
    /**
     * Merge strategy for auto-merge.
     */
    'merge_strategy'?: PullRequestSettingsMergeStrategyEnum;
}

export const PullRequestSettingsMergeStrategyEnum = {
    SQUASH: 'squash',
    MERGE: 'merge',
    REBASE: 'rebase'
} as const;

export type PullRequestSettingsMergeStrategyEnum = typeof PullRequestSettingsMergeStrategyEnum[keyof typeof PullRequestSettingsMergeStrategyEnum];


