/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Internal RunEvent-compatible JSON payload. The server validates this body by deserializing into the typed RunEvent struct. 
 */
export interface RunEvent {
    [key: string]: any;

    'id': string;
    'ts': string;
    'run_id': string;
    'node_id'?: string;
    'node_label'?: string;
    'session_id'?: string;
    'parent_session_id'?: string;
    /**
     * Event type discriminator.
     */
    'event': string;
    'properties'?: { [key: string]: any; };
}

