/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lifecycle status of a run. `archived` is a terminal status reached by an explicit user action on a previously terminal (`succeeded`, `failed`, or `dead`) run; archived runs are hidden from default listings and are read-only until unarchived. 
 */

export const RunStatus = {
    SUBMITTED: 'submitted',
    QUEUED: 'queued',
    STARTING: 'starting',
    RUNNING: 'running',
    BLOCKED: 'blocked',
    PAUSED: 'paused',
    REMOVING: 'removing',
    SUCCEEDED: 'succeeded',
    FAILED: 'failed',
    DEAD: 'dead',
    ARCHIVED: 'archived'
} as const;

export type RunStatus = typeof RunStatus[keyof typeof RunStatus];



