/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeState } from './node-state';
// May contain unused imports in some cases
// @ts-ignore
import type { RunCheckpoint } from './run-checkpoint';
// May contain unused imports in some cases
// @ts-ignore
import type { RunProjectionCheckpointsInnerInner } from './run-projection-checkpoints-inner-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusRecord } from './run-status-record';

/**
 * Raw internal run projection derived from the event log.
 */
export interface RunProjection {
    'run'?: { [key: string]: any; };
    'graph_source'?: string;
    'start'?: { [key: string]: any; };
    'status'?: RunStatusRecord | null;
    'checkpoint'?: RunCheckpoint | null;
    /**
     * Sequence-tagged checkpoint history entries as `[seq, checkpoint]`.
     */
    'checkpoints'?: Array<Array<RunProjectionCheckpointsInnerInner>>;
    'conclusion'?: { [key: string]: any; };
    'retro'?: { [key: string]: any; };
    'retro_prompt'?: string;
    'retro_response'?: string;
    'sandbox'?: { [key: string]: any; };
    'final_patch'?: string;
    'pull_request'?: { [key: string]: any; };
    /**
     * Map from StageId (`node_id@visit`) to NodeState.
     */
    'nodes': { [key: string]: NodeState; };
}

