/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lifecycle status of a run.
 */

export const RunStatus = {
    SUBMITTED: 'submitted',
    QUEUED: 'queued',
    STARTING: 'starting',
    RUNNING: 'running',
    BLOCKED: 'blocked',
    PAUSED: 'paused',
    REMOVING: 'removing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled'
} as const;

export type RunStatus = typeof RunStatus[keyof typeof RunStatus];



