/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DaytonaSettings } from './daytona-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { LocalSandboxSettings } from './local-sandbox-settings';

/**
 * Sandbox execution environment settings.
 */
export interface SandboxSettings {
    /**
     * Sandbox provider name.
     */
    'provider'?: string;
    /**
     * Whether to preserve the sandbox after the run.
     */
    'preserve'?: boolean;
    /**
     * Whether to use a devcontainer for the sandbox.
     */
    'devcontainer'?: boolean;
    'daytona'?: DaytonaSettings;
    'local'?: LocalSandboxSettings;
    /**
     * Environment variables injected into the sandbox.
     */
    'env'?: { [key: string]: string; };
}

