/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ServerSettingsExec {
    /**
     * Default exec provider.
     */
    'provider'?: string;
    /**
     * Default exec model.
     */
    'model'?: string;
    /**
     * Exec permission level.
     */
    'permissions'?: ServerSettingsExecPermissionsEnum;
    /**
     * Exec output format.
     */
    'output_format'?: ServerSettingsExecOutputFormatEnum;
}

export const ServerSettingsExecPermissionsEnum = {
    READ_ONLY: 'read-only',
    READ_WRITE: 'read-write',
    FULL: 'full'
} as const;

export type ServerSettingsExecPermissionsEnum = typeof ServerSettingsExecPermissionsEnum[keyof typeof ServerSettingsExecPermissionsEnum];
export const ServerSettingsExecOutputFormatEnum = {
    TEXT: 'text',
    JSON: 'json'
} as const;

export type ServerSettingsExecOutputFormatEnum = typeof ServerSettingsExecOutputFormatEnum[keyof typeof ServerSettingsExecOutputFormatEnum];


