/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiSettings } from './api-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ArtifactsSettings } from './artifacts-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { CheckpointSettings } from './checkpoint-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { Features } from './features';
// May contain unused imports in some cases
// @ts-ignore
import type { GitHubSettings } from './git-hub-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { GitSettings } from './git-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { HookDefinition } from './hook-definition';
// May contain unused imports in some cases
// @ts-ignore
import type { LlmSettings } from './llm-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { LogSettings } from './log-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { McpServerEntry } from './mcp-server-entry';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestSettings } from './pull-request-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxSettings } from './sandbox-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { SetupSettings } from './setup-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { WebSettings } from './web-settings';

/**
 * Structured server settings mirroring fabro_types::Settings.
 */
export interface ServerSettings {
    /**
     * Storage directory path.
     */
    'storage_dir'?: string;
    /**
     * Maximum concurrent runs.
     */
    'max_concurrent_runs'?: number;
    'web'?: WebSettings;
    'api'?: ApiSettings;
    'git'?: GitSettings;
    'features'?: Features;
    'log'?: LogSettings;
    /**
     * Default working directory.
     */
    'work_dir'?: string;
    'llm'?: LlmSettings;
    'setup'?: SetupSettings;
    'sandbox'?: SandboxSettings;
    /**
     * Default variable map.
     */
    'vars'?: { [key: string]: string; };
    'checkpoint'?: CheckpointSettings;
    'pull_request'?: PullRequestSettings;
    'hooks'?: Array<HookDefinition>;
    'artifacts'?: ArtifactsSettings;
    /**
     * Default MCP server configurations.
     */
    'mcp_servers'?: { [key: string]: McpServerEntry; };
    'github'?: GitHubSettings;
}

