/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Setup commands run before the workflow.
 */
export interface SetupSettings {
    /**
     * Shell commands to execute.
     */
    'commands': Array<string>;
    /**
     * Timeout per command in milliseconds.
     */
    'timeout_ms'?: number;
}

