/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SSH sandbox configuration for user-provided hosts.
 */
export interface SshSettings {
    /**
     * SSH destination (e.g. user@host or an SSH alias).
     */
    'destination': string;
    /**
     * Remote working directory.
     */
    'working_directory': string;
    /**
     * Optional path to a custom SSH config file.
     */
    'config_file'?: string;
}

