/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Optional reason attached to a run status transition.
 */

export const StatusReason = {
    COMPLETED: 'completed',
    PARTIAL_SUCCESS: 'partial_success',
    WORKFLOW_ERROR: 'workflow_error',
    CANCELLED: 'cancelled',
    TERMINATED: 'terminated',
    TRANSIENT_INFRA: 'transient_infra',
    BUDGET_EXHAUSTED: 'budget_exhausted',
    LAUNCH_FAILED: 'launch_failed',
    BOOTSTRAP_FAILED: 'bootstrap_failed',
    SANDBOX_INIT_FAILED: 'sandbox_init_failed',
    SANDBOX_INITIALIZING: 'sandbox_initializing'
} as const;

export type StatusReason = typeof StatusReason[keyof typeof StatusReason];



