/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FailureReason } from './failure-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusDead } from './run-status-dead';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusFailed } from './run-status-failed';
// May contain unused imports in some cases
// @ts-ignore
import type { RunStatusSucceeded } from './run-status-succeeded';

/**
 * @type TerminalStatus
 * Terminal run status captured inside an archived run.
 */
export type TerminalStatus = { kind: 'dead' } & RunStatusDead | { kind: 'failed' } & RunStatusFailed | { kind: 'succeeded' } & RunStatusSucceeded;


