/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Webhook delivery configuration.
 */
export interface WebhookSettings {
    /**
     * Webhook delivery strategy.
     */
    'strategy': WebhookSettingsStrategyEnum;
}

export const WebhookSettingsStrategyEnum = {
    TAILSCALE_FUNNEL: 'tailscale_funnel'
} as const;

export type WebhookSettingsStrategyEnum = typeof WebhookSettingsStrategyEnum[keyof typeof WebhookSettingsStrategyEnum];


