/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UsageByModel } from './usage-by-model';

/**
 * Aggregate token and cost usage across all runs since server start.
 */
export interface AggregateUsage {
    /**
     * Total number of completed runs.
     */
    'total_runs': number;
    /**
     * Total input tokens across all runs.
     */
    'total_input_tokens': number;
    /**
     * Total output tokens across all runs.
     */
    'total_output_tokens': number;
    /**
     * Total cost in USD across all runs.
     */
    'total_cost': number;
    /**
     * Total wall-clock runtime in seconds.
     */
    'total_runtime_secs': number;
    /**
     * Usage grouped by model.
     */
    'by_model': Array<UsageByModel>;
}

