/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SettingField } from './setting-field';

/**
 * A logical group of related settings.
 */
export interface SettingGroup {
    /**
     * Machine-readable group identifier.
     */
    'id': string;
    /**
     * Human-readable group name.
     */
    'name': string;
    /**
     * Prose description of the settings group.
     */
    'description': string;
    /**
     * Settings within this group.
     */
    'fields': Array<SettingField>;
}

