/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Input type for a setting field.
 */

export const SettingFieldType = {
    TEXT: 'text',
    SELECT: 'select',
    TOGGLE: 'toggle'
} as const;

export type SettingFieldType = typeof SettingFieldType[keyof typeof SettingFieldType];



