/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for sending inline steering guidance to a running agent.
 */
export interface SteerRequest {
    /**
     * File path to target with the guidance.
     */
    'file'?: string;
    /**
     * Line number in the file to annotate.
     */
    'line'?: number;
    /**
     * Guidance text for the agent.
     */
    'guidance': string;
}

