/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Token and cost usage for a single stage within a run.
 */
export interface UsageStage {
    /**
     * Human-readable stage name.
     */
    'stage': string;
    /**
     * Model slug used for this stage.
     */
    'model': string;
    /**
     * Number of input tokens consumed.
     */
    'input_tokens': number;
    /**
     * Number of output tokens generated.
     */
    'output_tokens': number;
    /**
     * Wall-clock runtime in seconds.
     */
    'runtime_secs': number;
    /**
     * Cost in USD for this stage.
     */
    'cost': number;
}

