/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Usage statistics grouped by model.
 */
export interface UsageByModel {
    /**
     * Model slug.
     */
    'model': string;
    /**
     * Number of stages that used this model.
     */
    'stages': number;
    /**
     * Total input tokens for this model.
     */
    'input_tokens': number;
    /**
     * Total output tokens for this model.
     */
    'output_tokens': number;
    /**
     * Total cost in USD for this model.
     */
    'cost': number;
}

