/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Result status of a verification control evaluation.
 */

export const VerificationStatus = {
    PASS: 'pass',
    FAIL: 'fail',
    NA: 'na'
} as const;

export type VerificationStatus = typeof VerificationStatus[keyof typeof VerificationStatus];



