/* tslint:disable */
/* eslint-disable */
/**
 * Arc Run API
 * HTTP API for managing Arc workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExecuteQueryRequest } from '../models';
// @ts-ignore
import type { ExecuteQueryResponse } from '../models';
// @ts-ignore
import type { HistoryEntry } from '../models';
// @ts-ignore
import type { SaveQueryRequest } from '../models';
// @ts-ignore
import type { SavedQuery } from '../models';
/**
 * InsightsApi - axios parameter creator
 */
export const InsightsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Saved Query
         * @param {SaveQueryRequest} saveQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSavedQuery: async (saveQueryRequest: SaveQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'saveQueryRequest' is not null or undefined
            assertParamExists('createSavedQuery', 'saveQueryRequest', saveQueryRequest)
            const localVarPath = `/insights/queries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(saveQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Saved Query
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSavedQuery: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSavedQuery', 'id', id)
            const localVarPath = `/insights/queries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Execute Query
         * @param {ExecuteQueryRequest} executeQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeQuery: async (executeQueryRequest: ExecuteQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'executeQueryRequest' is not null or undefined
            assertParamExists('executeQuery', 'executeQueryRequest', executeQueryRequest)
            const localVarPath = `/insights/execute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(executeQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Query History
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQueryHistory: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/insights/history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Saved Queries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSavedQueries: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/insights/queries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Saved Query
         * @param {string} id 
         * @param {SaveQueryRequest} saveQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSavedQuery: async (id: string, saveQueryRequest: SaveQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateSavedQuery', 'id', id)
            // verify required parameter 'saveQueryRequest' is not null or undefined
            assertParamExists('updateSavedQuery', 'saveQueryRequest', saveQueryRequest)
            const localVarPath = `/insights/queries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(saveQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InsightsApi - functional programming interface
 */
export const InsightsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InsightsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Saved Query
         * @param {SaveQueryRequest} saveQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSavedQuery(saveQueryRequest: SaveQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SavedQuery>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSavedQuery(saveQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InsightsApi.createSavedQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Saved Query
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSavedQuery(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSavedQuery(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InsightsApi.deleteSavedQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Execute Query
         * @param {ExecuteQueryRequest} executeQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async executeQuery(executeQueryRequest: ExecuteQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExecuteQueryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.executeQuery(executeQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InsightsApi.executeQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Query History
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listQueryHistory(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<HistoryEntry>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listQueryHistory(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InsightsApi.listQueryHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Saved Queries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSavedQueries(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SavedQuery>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSavedQueries(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InsightsApi.listSavedQueries']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Saved Query
         * @param {string} id 
         * @param {SaveQueryRequest} saveQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSavedQuery(id: string, saveQueryRequest: SaveQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SavedQuery>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSavedQuery(id, saveQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InsightsApi.updateSavedQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InsightsApi - factory interface
 */
export const InsightsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InsightsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Saved Query
         * @param {SaveQueryRequest} saveQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSavedQuery(saveQueryRequest: SaveQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<SavedQuery> {
            return localVarFp.createSavedQuery(saveQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Saved Query
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSavedQuery(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSavedQuery(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Execute Query
         * @param {ExecuteQueryRequest} executeQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        executeQuery(executeQueryRequest: ExecuteQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExecuteQueryResponse> {
            return localVarFp.executeQuery(executeQueryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Query History
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listQueryHistory(options?: RawAxiosRequestConfig): AxiosPromise<Array<HistoryEntry>> {
            return localVarFp.listQueryHistory(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Saved Queries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSavedQueries(options?: RawAxiosRequestConfig): AxiosPromise<Array<SavedQuery>> {
            return localVarFp.listSavedQueries(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Saved Query
         * @param {string} id 
         * @param {SaveQueryRequest} saveQueryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSavedQuery(id: string, saveQueryRequest: SaveQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<SavedQuery> {
            return localVarFp.updateSavedQuery(id, saveQueryRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InsightsApi - object-oriented interface
 */
export class InsightsApi extends BaseAPI {
    /**
     * 
     * @summary Create Saved Query
     * @param {SaveQueryRequest} saveQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSavedQuery(saveQueryRequest: SaveQueryRequest, options?: RawAxiosRequestConfig) {
        return InsightsApiFp(this.configuration).createSavedQuery(saveQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Saved Query
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteSavedQuery(id: string, options?: RawAxiosRequestConfig) {
        return InsightsApiFp(this.configuration).deleteSavedQuery(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Execute Query
     * @param {ExecuteQueryRequest} executeQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public executeQuery(executeQueryRequest: ExecuteQueryRequest, options?: RawAxiosRequestConfig) {
        return InsightsApiFp(this.configuration).executeQuery(executeQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Query History
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listQueryHistory(options?: RawAxiosRequestConfig) {
        return InsightsApiFp(this.configuration).listQueryHistory(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Saved Queries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSavedQueries(options?: RawAxiosRequestConfig) {
        return InsightsApiFp(this.configuration).listSavedQueries(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Saved Query
     * @param {string} id 
     * @param {SaveQueryRequest} saveQueryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateSavedQuery(id: string, saveQueryRequest: SaveQueryRequest, options?: RawAxiosRequestConfig) {
        return InsightsApiFp(this.configuration).updateSavedQuery(id, saveQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

